on:
  push:
    tags: ["v*"]

jobs:
  release:
    name: Release VHS Extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: vhs
          push-to: eth0net/zed-extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.EXTENSIONS_TOKEN }}
